DROP TABLE IF EXISTS people;
DROP TABLE IF EXISTS samples;
DROP TABLE IF EXISTS genres;
DROP TABLE IF EXISTS categories;

CREATE TABLE people (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT UNIQUE NOT NULL
);

CREATE TABLE samples (
	person INTEGER NOT NULL,
	category INTEGER NOT NULL,
	stamp DATETIME DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (person) REFERENCES people (id),
	FOREIGN KEY (category) REFERENCES categories (id)
);

CREATE TABLE genres (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT UNIQUE NOT NULL
);

CREATE TABLE categories (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL,
	genre INTEGER NOT NULL,
	FOREIGN KEY (genre) REFERENCES genres (id),
	UNIQUE (name, genre)
);
